### PR TITLE
Sass 105: Updating the content for the start page

### PR DESCRIPTION
**Pull request by joeyymoore**

### CODE REVIEW

**Review by robert-webb-hmrc — CHANGES_REQUESTED** [review]
Changes to in body content look good, there are a couple of discrepancies with the service header, the breadcrumbs and the caption however (Image attached for reference)

Screenshot 2021-02-11 at 10 21 01

**Comment by robert-webb-hmrc** [comment]
Screenshot 2021-02-11 at 10 29 35

For reference, prototype above

**Comment by BenCosfordHMRC** [comment]
For the service header I think you'll want to rebase as the header should be correct. 

@robert-webb-hmrc your other two comments are valid but we thought that the breadcrumbs one would be completed as part of the breadcrumbs ticket. 

& similarly the subheading update be done as part of another ticket to change them all to the same thing. @joeyymoore could you check we have a ticket for the date subheading

**Comment by BenCosfordHMRC** [comment]
Looking at the subheadings it would only be two places in income FE actually (personal FE has different headings), maybe even one message key so it might be easier to update as part of this? @joeyymoore @robert-webb-hmrc thoughts?

**Comment by robert-webb-hmrc** [comment]
So the subheading as per SASS-300 should be "submit" rather than "Submit". This is the case in this frontend as well as the PITSF

**Comment by BenCosfordHMRC** [comment]
> So the subheading as per SASS-300 should be "submit" rather than "Submit". This is the case in this frontend as well as the PITSF

good point you're right

**Review by robert-webb-hmrc — APPROVED** [review]

**Pull request merged**
